ktor {
    deployment {
        sslPort = 8080
    }
    application {
        modules = [ com.pesegato.a10s.AnkylosaurusKt.module ]
    }
    security {
        ssl {
            keyStore = ${?CERT_PATH}
            keyStorePassword = "password"
            keyAlias = "alias"
            privateKeyPassword = "password"
            enabledProtocols = ["TLSv1.3"]
        }
    }
}